language: ruby
branches:
  only:
    - master
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  #- jruby-18mode
  #- jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    #- jruby-head
notifications:
  recipients:
    - yann.lugrin@sans-savoir.net
